version: '3'
services:
  db:
    image: mongo
  server:
        build: .
        command: npm run start-server
        volumes:
              - .:/usr/src/app
        ports:
              - "3001:3001"
        depends_on:
              - db
  client:
      build: .
      command: npm run start-client
      volumes:
            - .:/usr/src/app
      ports:
            - "3000:3000"
