version: '3'
services:
  db:
    image: mongo
  web:
      build: .
      command: npm run start-server && npm run start-client
      volumes:
            - .:/usr/src/app
      ports:
            - "3000:3000"
            - "3001:3001"
      depends_on:
            - db